name: itchio_push

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUTLER_API_KEY: ${{ secrets.butler }}
      PICO_URL: ${{ secrets.pico }}
    steps:
    - uses: actions/checkout@v2
    - name: Push zip of cart to itch.io
      run: |
        curl -L -o pico.zip $PICO_URL
        unzip pico.zip
        chmod +x pico-8/pico8
        ./pico-8/pico8 -x build.p8
        rm -rf ~/.lexaloffle/pico-8/carts/*
        cp *.p8 ~/.lexaloffle/pico-8/carts/
        ./pico-8/pico8 -x build.p8
        zip -r 7drl_rogue.zip ~/.lexaloffle/pico-8/carts/rogue_html
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler push 7drl_rogue.zip iceboxr/rogue-dealer:html
        
